language: go

go:
  - "1.12.x"
  - "1.13.x"

before_install:
  - go mod download
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo

script:
  - go test ./parser -coverprofile=coverage.txt -covermode=atomic
  - golint -set_exit_status ./...
  - gocyclo -over 15 ./parser

after_success:
  - bash <(curl -s https://codecov.io/bash)
